development:
  adapter: sqlite3
  database: db/development_database.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test_database.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production_database.db
  pool: 5
  timeout: 5000

